---
title: "R Notebook"
output: html_notebook
---

```{r}
library(psych)
```


```{r}
##language
language<-d_imp2%>%select(vocabprocess_processing_speed_target,bpvs_raw)

language.m<-fa.parallel(language,fm='ml',fa='pc')

language.pc<-principal(language,nfactors = 1,rotate='varimax')
summary(language.pc)
language.pc$loadings
fa.diagram(language.pc,simple=T)
factor.plot(language.pc$loadings,labels = rownames(language.pc$loadings))
```

```{r}
##social
social<-d_imp2%>%select(tomi_early,tomi_basic,tomi_advanced,et_figurestask_dwell_time_interacting,et_falsebelief_Testtrial_dwell_time_to_correct)

social.m<-fa.parallel(social,fm='ml',fa='pc')

social.pc<-principal(social,nfactors = 1,rotate = 'varimax')
summary(social.pc)
social.pc$loadings
fa.diagram(social.pc,simple=T)
factor.plot(social.pc$loadings,labels = rownames(social.pc$loadings))
```

```{r}
exe<-d_imp2%>%select(mean_brief,flanker_percenterrors_congruent,flanker_percenterrors_incongruent,flanker_mean_rt_congruent,flanker_mean_rt_incongruent,pvt_mean_rt,pvt_mean_lapse_rt,pvt_number_of_lapses)

exe.m<-fa.parallel(exe,fm='ml',fa='pc')

exe.pc<-principal(exe,nfactors = 1,rotate = 'varimax')
summary(exe.pc)
exe.pc$loadings
fa.diagram(exe.pc,simple=T)
factor.plot(exe.pc$loadings,labels = rownames(exe.pc$loadings))
```
##language regression
```{r}
language_lm<-lm(language.pc$loadings[1]*vocabprocess_processing_speed_target+language.pc$loadings[2]*bpvs_raw~bilec_total_input+wasi_sum_rawscores+age_m,data=scale_d)
summary(language_lm)
```


```{r}
non_au_language_lm<-lm(language.pc$loadings[1]*vocabprocess_processing_speed_target+language.pc$loadings[2]*bpvs_raw~bilec_total_input+wasi_sum_rawscores+age_m,data=d_non_au)
summary(non_au_language_lm)


au_language_lm<-lm(language.pc$loadings[1]*vocabprocess_processing_speed_target+language.pc$loadings[2]*bpvs_raw~bilec_total_input+wasi_sum_rawscores+age_m,data=d_au)
summary(au_language_lm)
```



##social regression
```{r}
social_lm<-lm(social.pc$loadings[1]*tomi_early+social.pc$loadings[2]*tomi_basic+social.pc$loadings[3]*tomi_advanced+social.pc$loadings[4]*et_figurestask_dwell_time_interacting+social.pc$loadings[5]*et_falsebelief_Testtrial_dwell_time_to_correct ~ bilec_total_input+wasi_sum_rawscores+age_m,data=d_imp2)
summary(social_lm)
```
```{r}
non_au_social_lm<-lm(social.pc$loadings[1]*tomi_early+social.pc$loadings[2]*tomi_basic+social.pc$loadings[3]*tomi_advanced+social.pc$loadings[4]*et_figurestask_dwell_time_interacting+social.pc$loadings[5]*et_falsebelief_Testtrial_dwell_time_to_correct ~ bilec_total_input+wasi_sum_rawscores+age_m,data=d_non_au)
summary(non_au_social_lm)


au_social_lm<-lm(social.pc$loadings[1]*tomi_early+social.pc$loadings[2]*tomi_basic+social.pc$loadings[3]*tomi_advanced+social.pc$loadings[4]*et_figurestask_dwell_time_interacting+social.pc$loadings[5]*et_falsebelief_Testtrial_dwell_time_to_correct ~ bilec_total_input+wasi_sum_rawscores+age_m,data=d_au)
summary(au_social_lm)
```


##exe regression
```{r}
exe_lm<-lm(exe.pc$loadings[1]*mean_brief+exe.pc$loadings[2]*flanker_percenterrors_congruent+exe.pc$loadings[3]*flanker_percenterrors_incongruent+exe.pc$loadings[4]*flanker_mean_rt_congruent+exe.pc$loadings[5]*flanker_mean_rt_incongruent +exe.pc$loadings[6]*pvt_mean_rt+exe.pc$loadings[7]*pvt_mean_lapse_rt+exe.pc$loadings[8]*pvt_number_of_lapses~ bilec_total_input+wasi_sum_rawscores+age_m,data=d_imp2)
summary(exe_lm)
```

```{r}
non_au_exe_lm<-lm(exe.pc$loadings[1]*mean_brief+exe.pc$loadings[2]*flanker_percenterrors_congruent+exe.pc$loadings[3]*flanker_percenterrors_incongruent+exe.pc$loadings[4]*flanker_mean_rt_congruent+exe.pc$loadings[5]*flanker_mean_rt_incongruent +exe.pc$loadings[6]*pvt_mean_rt+exe.pc$loadings[7]*pvt_mean_lapse_rt+exe.pc$loadings[8]*pvt_number_of_lapses~ bilec_total_input+wasi_sum_rawscores+age_m,data=d_non_au)
summary(non_au_exe_lm)


au_exe_lm<-lm(exe.pc$loadings[1]*mean_brief+exe.pc$loadings[2]*flanker_percenterrors_congruent+exe.pc$loadings[3]*flanker_percenterrors_incongruent+exe.pc$loadings[4]*flanker_mean_rt_congruent+exe.pc$loadings[5]*flanker_mean_rt_incongruent +exe.pc$loadings[6]*pvt_mean_rt+exe.pc$loadings[7]*pvt_mean_lapse_rt+exe.pc$loadings[8]*pvt_number_of_lapses~ bilec_total_input+wasi_sum_rawscores+age_m,data=d_au)
summary(au_exe_lm)
```


