---
title: "R Notebook"
output: html_notebook
---


```{r}
library(lmerTest)
```

```{r}
language_model<-'
        ##latent variables
        
        language=~vocabprocess_processing_speed_target+bpvs_raw+wasi_sum_rawscores'



language_cfa<-cfa(language_model,data=scale_d,estimator="MLF")
s_lan<-summary(language_cfa, standardized = TRUE, fit.measures=TRUE)
semPaths(language_cfa,what =  'est', layout = 'tree')
semPaths(language_cfa,what =  'std', layout = 'tree')
fitmeasures(language_cfa,c('chisq','df','pvalue','gfi','rmsea','cfi','aic','tli'))
```
```{r}
cfa_value<-lavPredict(language_cfa)

language_lm_non_au<-lm(cfa_value[1:51,1]~bilec_total_input,data=d_non_au)
summary(language_lm_non_au)
language_lm_au<-lm(cfa_value[52:89,1]~bilec_total_input,data=d_au)
summary(language_lm_au)
```

```{r}
social_model<-'
        ##latent variables
        social=~tomi_early+tomi_basic+tomi_advanced+et_figurestask_dwell_time_interacting+et_falsebelief_Testtrial_dwell_time_to_correct+tom_tb_totalscore'

social_cfa<-cfa(social_model,data=scale_d,estimator="MLF")
s_soc<-summary(social_cfa, standardized = TRUE, fit.measures=TRUE)
semPaths(social_cfa,what =  'est', layout = 'tree')
semPaths(social_cfa,what =  'std', layout = 'tree')
fitmeasures(social_cfa,c('chisq','df','pvalue','gfi','rmsea','cfi','aic','tli'))
```
##social regression
```{r}
cfa_value<-lavPredict(social_cfa)

social_lm_non_au<-lm(cfa_value[1:51,1]~bilec_total_input,data=d_non_au)
summary(social_lm_non_au)
social_lm_au<-lm(cfa_value[52:89,1]~bilec_total_input,data=d_au)
summary(social_lm_au)
```

```{r}
exe_model<-'
        ##latent variables
        exe=~mean_brief+flanker_percenterrors_congruent+flanker_percenterrors_incongruent+flanker_mean_rt_congruent+flanker_mean_rt_incongruent+pvt_mean_rt+pvt_number_of_lapses'

exe_cfa<-cfa(exe_model,data=scale_d,estimator="MLF")
s_exe<-summary(exe_cfa, standardized = TRUE, fit.measures=TRUE)
semPaths(exe_cfa,what =  'est', layout = 'tree')
semPaths(exe_cfa,what =  'std', layout = 'tree')
fitmeasures(exe_cfa,c('chisq','df','pvalue','gfi','rmsea','cfi','aic','tli'))
```




```{r}
        flanker_mean_rt_congruent	~~	flanker_mean_rt_incongruent
        flanker_percenterrors_congruent	~~	flanker_percenterrors_incongruent
        flanker_mean_rt_incongruent	~~	pvt_number_of_lapses
        flanker_percenterrors_congruent	~~	flanker_mean_rt_congruent
        flanker_percenterrors_incongruent	~~	pvt_mean_rt
        pvt_mean_rt	~~	pvt_number_of_lapses
        et_figurestask_dwell_time_interacting	~~	et_falsebelief_Testtrial_dwell_time_to_correct
        mean_brief	~~	flanker_mean_rt_congruent
        flanker_percenterrors_incongruent	~~	pvt_number_of_lapses
        mean_brief	~~	pvt_number_of_lapses
        mean_brief	~~	flanker_mean_rt_incongruent
```


